research_task:
  description: >
    Conduct thorough research on {topic} to uncover interesting, relevant, and current insights that will form the foundation of a tweet.
  expected_output: >
    Return relevant and engaging insights about {topic}, The year is 2024.
  agent: research_agent

drafting_task:
  description: >
    Based on the research findings, create three tweet drafts that vary in format, tone, and content. The year is 2024.
    Examples of draft types include:
    - A fact-based tweet with engaging statistics or facts.
    - A question to engage the audience and prompt interaction.
    - A witty or thought-provoking one-liner.
    The user will be presented with these drafts.
  expected_output: >
    Three tweet drafts with clear differentiation in style and content, ready for user review and selection.
  agent: drafting_agent
  context: ["research_task"]
